version: '3.8'

services:
  web:
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../html:/usr/share/nginx/html
      - ../html/static:/usr/share/nginx/html/static